name: "Helm Chart Releaser"
description: "Build and Release Helm Charts"
author: "Data Biosphere"
branding:
  icon: git-merge
  color: purple
runs:
  using: 'docker'
  image: docker://us-central1-docker.pkg.dev/dsp-artifact-registry/github-actions-public/chart-releaser:0.7.0
