name: 'render'
description: 'Renders Terra's Kubernetes manifests '
inputs:
  outdir:
    description: 'Directory where manifests rendered to.'
    required: true
  srcdir:
    description: "Directory where render script lives."
runs:
  using: 'docker'
  # This image is built from the terra-helmfile-images repo:
  #   https://github.com/broadinstitute/terra-helmfile-images
  image: 'us-central1-docker.pkg.dev/dsp-artifact-registry/terra-helmfile-images/argocd-custom-image:main'
  args:
  - ${{ inputs.outdir }}
  - ${{ inputs.srcdir }}
