name: Release Actions
on:
  push:
    branches:
      - master
    paths:
      - 'actions/**'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Bump version and push tags
      uses: docker://us-central1-docker.pkg.dev/dsp-artifact-registry/github-actions-public/action-releaser:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
